PR para resolver a issue #5 - Scan da imagem docker
DadosAbertosDeFeira/iac-docker-tika pull request #6
Opened 2021-06-20 14:38 UTC by mmmarceleza

Prezados, segue o PR para o _scan_ da imagem, referente à issue #5 

O último _job_ que adicionei quebra o _CI_ porque encontra vulnerabilidades na imagem gerada no _build_. Fiz um teste local aqui com a versão seguinte (`1.26`) e não encontrei problemas do nível `HIGH` ou `CRITICAL`. Sugiro subir a versão para `1.26`.

Outra observação, há como alterar a saída do CI de `fail` para `warnig` quando encontrar uma saída de erro? Se sim, daria para colocar dessa forma ao encontrar vulnerabilidades nesse _job_, o que acham?

Também fiz uma melhoria no README, me passem o _feedback_ se ficou bom.

2021-06-20 16:57 UTC, gomex requested changes
Está ficando muito bom!

2021-06-20 16:57 UTC, gomex commented on .github/workflows/main.yml
> +          severity: 'CRITICAL,HIGH'
Isso pode funcionar antes do push? Se sim, seria o ideal.

2021-06-20 17:59 UTC, mmmarceleza commented on .github/workflows/main.yml
> +          severity: 'CRITICAL,HIGH'
Pode sim, roda independentemente dos outros _jobs_ se quisermos. Eu acabei deixando no fim porque imaginei que seria usado apenas como um informativo. Pode acontecer de surgir uma vulnerabilidade que ainda não tem correção. Podemos discutir isso com calma depois.

2021-06-27 18:12 UTC, mmmarceleza commented
@gomex, fiz as correções. Só fiquei na dúvida se a publicação da imagem para Docker Hub era nos _commits_ para o `main` ou na criação de tags. Na semana passada eu deveria ter anotado.

2021-07-09 12:59 UTC, edsoncelio commented
> @gomex, fiz as correções. Só fiquei na dúvida se a publicação da imagem para Docker Hub era nos _commits_ para o `main` ou na criação de tags. Na semana passada eu deveria ter anotado.

Opa @mmmarceleza, o push para o docker hub é feito com base em branch, na `main`, nesse caso:        
 `if: github.ref == 'refs/heads/main'`

2021-07-09 13:56 UTC, edsoncelio commented
Muito bom @mmmarceleza, seguem alguns pontos que identifiquei/fiquei em dúvida:

1. Dado que o passo de `scan` vai executar sempre, poderíamos deixar a execução apenas em `pull_request`, com isso a gente ia garantir que em `main` vai sempre ter executado esse passo (ficaria como pré-requisito) e o passo de `push` faria apenas a publicação do container, o que acha?
2. Nessas linhas ([aqui](https://github.com/mmmarceleza/iac-docker-tika/blob/babba72e1e8834415656f3db3b627e8715a72f9f/.github/workflows/main.yml#L78) e [aqui](https://github.com/mmmarceleza/iac-docker-tika/blob/babba72e1e8834415656f3db3b627e8715a72f9f/.github/workflows/main.yml#L83)) não seria melhor nomear com o nome certinho do repo? algo como `iac-docker-tika:....`
3. No seu repositório o CI está falhando, pode dar uma olhada nisso?

2021-07-09 16:05 UTC, mmmarceleza commented
> Muito bom @mmmarceleza, seguem alguns pontos que identifiquei/fiquei em dúvida:
> 
> 1. Dado que o passo de `scan` vai executar sempre, poderíamos deixar a execução apenas em `pull_request`, com isso a gente ia garantir que `push` em `main` vai sempre ter executado esse passo (ficaria como pré-requisito) e o passo de `push` faria apenas a publicação do container, o que acha?
> 2. Nessas linhas ([aqui](https://github.com/mmmarceleza/iac-docker-tika/blob/babba72e1e8834415656f3db3b627e8715a72f9f/.github/workflows/main.yml#L78) e [aqui](https://github.com/mmmarceleza/iac-docker-tika/blob/babba72e1e8834415656f3db3b627e8715a72f9f/.github/workflows/main.yml#L83)) não seria melhor nomear com o nome certinho do repo? algo como `iac-docker-tika:....`
> 3. No seu repositório o CI está falhando, pode dar uma olhada nisso?

Fala @edsoncelio , tudo bom? Grato pela análise feita nas modificações. Vou acertar esses pontos amanhã, na dúvida te pingo. O item 3 foi o que mais me encabulou, cadastrei as secrets do meu Docker Hub pessoal e não funcionou. Amanhã faço novas tentativas. 

Valeu!

2021-07-11 15:32 UTC, mmmarceleza commented
> Muito bom @mmmarceleza, seguem alguns pontos que identifiquei/fiquei em dúvida:
> 
> 1. Dado que o passo de `scan` vai executar sempre, poderíamos deixar a execução apenas em `pull_request`, com isso a gente ia garantir que `push` em `main` vai sempre ter executado esse passo (ficaria como pré-requisito) e o passo de `push` faria apenas a publicação do container, o que acha?
> 2. Nessas linhas ([aqui](https://github.com/mmmarceleza/iac-docker-tika/blob/babba72e1e8834415656f3db3b627e8715a72f9f/.github/workflows/main.yml#L78) e [aqui](https://github.com/mmmarceleza/iac-docker-tika/blob/babba72e1e8834415656f3db3b627e8715a72f9f/.github/workflows/main.yml#L83)) não seria melhor nomear com o nome certinho do repo? algo como `iac-docker-tika:....`
> 3. No seu repositório o CI está falhando, pode dar uma olhada nisso?

@edsoncelio , fiquei na dúvida em relação ao item 1, poderia dar mais detalhes? Quanto aos outros pontos eu já atendi, corrigi o CI e troquei o nome da imagem na etapa do scan. 

Curiosidade: a versão que não tinha vulnerabilidade dos níveis HIGH e CRITICAL, foi lançada a 4 dias atrás.

2021-07-11 17:29 UTC, somatorio approved these changes
O item levantado pelo @edsoncelio me pareceu mais uma melhoria do que requisito, então acho que podemos fazer o merge agora para já termos isso e fazer um novo PR depois com a mudança proposta

2021-07-11 17:56 UTC, merged